name: Build Web Version

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: godot-driller

jobs:
  build-web:
    name: Build Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Export Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          cp -r /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Web
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build-${{ github.sha }}
          path: build/web
          retention-days: 14

  deploy-preview:
    name: Deploy PR Preview
    needs: build-web
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build-${{ github.sha }}
          path: build/web

      - name: Deploy PR Preview to GitHub Pages
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build/web
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Add PR Comment with Preview Link
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const previewUrl = `https://${owner}.github.io/${repo}/pr-preview/pr-${prNumber}/`;
            const artifactUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;

            const comment = `## 🎮 Web Build Ready!

            The web build for this PR is complete and deployed!

            ### 🚀 [**Try it now!**](${previewUrl})

            Click the link above to test the game directly in your browser - no download needed!

            ---

            <details>
            <summary>Alternative: Download artifact</summary>

            **To test locally:**
            1. Visit the [workflow run](${artifactUrl})
            2. Download the \`web-build-${{ github.sha }}\` artifact
            3. Extract the zip file
            4. Serve the files using a local web server:
               \`\`\`bash
               python -m http.server 8000
               # or
               npx serve .
               \`\`\`
            5. Open http://localhost:8000/index.html in your browser

            **Note:** The artifact will be available for 14 days.
            </details>`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: owner,
              repo: repo,
              body: comment
            });

  deploy-main:
    name: Deploy to GitHub Pages (Main)
    needs: build-web
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build-${{ github.sha }}
          path: build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          keep_files: true
