name: Build Web Version

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  GODOT_VERSION: 4.5
  EXPORT_NAME: godot-driller

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Export Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          cp -r /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Web
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build-${{ github.sha }}
          path: build/web
          retention-days: 14

      - name: Install Surge
        if: github.event_name == 'pull_request'
        run: npm install -g surge

      - name: Deploy to Surge
        if: github.event_name == 'pull_request'
        id: surge-deployment
        run: |
          surge build/web ${{ env.EXPORT_NAME }}-pr-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
          echo "url=${{ env.EXPORT_NAME }}-pr-${{ github.event.pull_request.number }}.surge.sh" >> $GITHUB_OUTPUT

      - name: Add PR Comment with Preview Link
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://${{ steps.surge-deployment.outputs.url }}`;
            const artifactUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            const comment = `## 🎮 Web Build Ready!\n\nThe web build for this PR is complete and deployed!\n\n### 🚀 [**Try it now!**](${previewUrl})\n\nClick the link above to test the game directly in your browser - no download needed!\n\n---\n\n<details>\n<summary>Alternative: Download artifact</summary>\n\n**To test locally:**\n1. Visit the [workflow run](${artifactUrl})\n2. Download the \`web-build-${{ github.sha }}\` artifact\n3. Extract the zip file\n4. Serve the files using a local web server:\n   \`\`\`bash\n   python -m http.server 8000\n   # or\n   npx serve .\n   \`\`\`\n5. Open http://localhost:8000/index.html in your browser\n\n**Note:** The artifact will be available for 14 days.\n</details>`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: false
